// Code generated by MockGen. DO NOT EDIT.
// Source: grpc.go
//
// Generated by this command:
//
//	mockgen -source=grpc.go -destination=grpc_mocks_test.go -package=grpcp2platency_test
//

// Package grpcp2platency_test is a generated GoMock package.
package grpcptp_test

// import (
// 	context "context"
// 	reflect "reflect"

// 	pollpb "github.com/wafer-bw/jittermon/internal/gen/go/poll/v1"
// 	recorder "github.com/wafer-bw/jittermon/internal/recorder"
// 	gomock "go.uber.org/mock/gomock"
// 	grpc "google.golang.org/grpc"
// )

// // MockRecorder is a mock of Recorder interface.
// type MockRecorder struct {
// 	ctrl     *gomock.Controller
// 	recorder *MockRecorderMockRecorder
// 	isgomock struct{}
// }

// // MockRecorderMockRecorder is the mock recorder for MockRecorder.
// type MockRecorderMockRecorder struct {
// 	mock *MockRecorder
// }

// // NewMockRecorder creates a new mock instance.
// func NewMockRecorder(ctrl *gomock.Controller) *MockRecorder {
// 	mock := &MockRecorder{ctrl: ctrl}
// 	mock.recorder = &MockRecorderMockRecorder{mock}
// 	return mock
// }

// // EXPECT returns an object that allows the caller to indicate expected use.
// func (m *MockRecorder) EXPECT() *MockRecorderMockRecorder {
// 	return m.recorder
// }

// // Record mocks base method.
// func (m *MockRecorder) Record(arg0 context.Context, arg1 recorder.Sample) {
// 	m.ctrl.T.Helper()
// 	m.ctrl.Call(m, "Record", arg0, arg1)
// }

// // Record indicates an expected call of Record.
// func (mr *MockRecorderMockRecorder) Record(arg0, arg1 any) *gomock.Call {
// 	mr.mock.ctrl.T.Helper()
// 	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockRecorder)(nil).Record), arg0, arg1)
// }

// // MockClientPoller is a mock of ClientPoller interface.
// type MockClientPoller struct {
// 	ctrl     *gomock.Controller
// 	recorder *MockClientPollerMockRecorder
// 	isgomock struct{}
// }

// // MockClientPollerMockRecorder is the mock recorder for MockClientPoller.
// type MockClientPollerMockRecorder struct {
// 	mock *MockClientPoller
// }

// // NewMockClientPoller creates a new mock instance.
// func NewMockClientPoller(ctrl *gomock.Controller) *MockClientPoller {
// 	mock := &MockClientPoller{ctrl: ctrl}
// 	mock.recorder = &MockClientPollerMockRecorder{mock}
// 	return mock
// }

// // EXPECT returns an object that allows the caller to indicate expected use.
// func (m *MockClientPoller) EXPECT() *MockClientPollerMockRecorder {
// 	return m.recorder
// }

// // Poll mocks base method.
// func (m *MockClientPoller) Poll(ctx context.Context, in *pollpb.PollRequest, opts ...grpc.CallOption) (*pollpb.PollResponse, error) {
// 	m.ctrl.T.Helper()
// 	varargs := []any{ctx, in}
// 	for _, a := range opts {
// 		varargs = append(varargs, a)
// 	}
// 	ret := m.ctrl.Call(m, "Poll", varargs...)
// 	ret0, _ := ret[0].(*pollpb.PollResponse)
// 	ret1, _ := ret[1].(error)
// 	return ret0, ret1
// }

// // Poll indicates an expected call of Poll.
// func (mr *MockClientPollerMockRecorder) Poll(ctx, in any, opts ...any) *gomock.Call {
// 	mr.mock.ctrl.T.Helper()
// 	varargs := append([]any{ctx, in}, opts...)
// 	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockClientPoller)(nil).Poll), varargs...)
// }
