// Code generated by MockGen. DO NOT EDIT.
// Source: peer_export_test.go
//
// Generated by this command:
//
//	mockgen -source=peer_export_test.go -destination=peer_mocks_test.go -package=peer_test Recorder,PollServiceClient
//

// Package peer_test is a generated GoMock package.
package peer_test

import (
	context "context"
	reflect "reflect"

	pollpb "github.com/wafer-bw/jittermon/internal/pb/pollpb"
	recorder "github.com/wafer-bw/jittermon/internal/recorder"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockRecorder is a mock of Recorder interface.
type MockRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockRecorderMockRecorder
	isgomock struct{}
}

// MockRecorderMockRecorder is the mock recorder for MockRecorder.
type MockRecorderMockRecorder struct {
	mock *MockRecorder
}

// NewMockRecorder creates a new mock instance.
func NewMockRecorder(ctrl *gomock.Controller) *MockRecorder {
	mock := &MockRecorder{ctrl: ctrl}
	mock.recorder = &MockRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecorder) EXPECT() *MockRecorderMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockRecorder) Record(arg0 context.Context, arg1 recorder.Sample) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Record", arg0, arg1)
}

// Record indicates an expected call of Record.
func (mr *MockRecorderMockRecorder) Record(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockRecorder)(nil).Record), arg0, arg1)
}

// MockPollServiceClient is a mock of PollServiceClient interface.
type MockPollServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockPollServiceClientMockRecorder
	isgomock struct{}
}

// MockPollServiceClientMockRecorder is the mock recorder for MockPollServiceClient.
type MockPollServiceClientMockRecorder struct {
	mock *MockPollServiceClient
}

// NewMockPollServiceClient creates a new mock instance.
func NewMockPollServiceClient(ctrl *gomock.Controller) *MockPollServiceClient {
	mock := &MockPollServiceClient{ctrl: ctrl}
	mock.recorder = &MockPollServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPollServiceClient) EXPECT() *MockPollServiceClientMockRecorder {
	return m.recorder
}

// Poll mocks base method.
func (m *MockPollServiceClient) Poll(ctx context.Context, in *pollpb.PollRequest, opts ...grpc.CallOption) (*pollpb.PollResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Poll", varargs...)
	ret0, _ := ret[0].(*pollpb.PollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Poll indicates an expected call of Poll.
func (mr *MockPollServiceClientMockRecorder) Poll(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockPollServiceClient)(nil).Poll), varargs...)
}
