// Code generated by MockGen. DO NOT EDIT.
// Source: peer_export_test.go
//
// Generated by this command:
//
//	mockgen -source=peer_export_test.go -destination=peer_mocks_test.go -package=peer_test Recorder,PollServiceClient
//

// Package peer_test is a generated GoMock package.
package peer_test
