// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.2
// source: internal/sampler/p2platency/internal/grpcpeer/proto/poll_response.proto

package pollpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PollResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Jitter      *durationpb.Duration   `protobuf:"bytes,2,opt,name=jitter"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PollResponse) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *PollResponse) GetJitter() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Jitter
	}
	return nil
}

func (x *PollResponse) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *PollResponse) SetJitter(v *durationpb.Duration) {
	x.xxx_hidden_Jitter = v
}

func (x *PollResponse) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *PollResponse) HasJitter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Jitter != nil
}

func (x *PollResponse) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *PollResponse) ClearJitter() {
	x.xxx_hidden_Jitter = nil
}

type PollResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The identity of the responding peer.
	Id *string
	// The jitter observed by the responding peer on incoming requests.
	Jitter *durationpb.Duration
}

func (b0 PollResponse_builder) Build() *PollResponse {
	m0 := &PollResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_Jitter = b.Jitter
	return m0
}

var File_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto protoreflect.FileDescriptor

var file_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto_rawDesc = string([]byte{
	0x0a, 0x47, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x72, 0x2f, 0x70, 0x32, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x70, 0x65, 0x65, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6c, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x6f, 0x6c, 0x6c, 0x1a,
	0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x51, 0x0a, 0x0c, 0x50, 0x6f, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x31, 0x0a, 0x06, 0x6a, 0x69, 0x74, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x6a, 0x69, 0x74, 0x74,
	0x65, 0x72, 0x42, 0x54, 0x5a, 0x52, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x77, 0x61, 0x66, 0x65, 0x72, 0x2d, 0x62, 0x77, 0x2f, 0x6a, 0x69, 0x74, 0x74, 0x65, 0x72,
	0x6d, 0x6f, 0x6e, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x72, 0x2f, 0x70, 0x32, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x70, 0x65, 0x65,
	0x72, 0x2f, 0x70, 0x6f, 0x6c, 0x6c, 0x70, 0x62, 0x62, 0x08, 0x65, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x70, 0xe8, 0x07,
})

var file_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto_goTypes = []any{
	(*PollResponse)(nil),        // 0: poll.PollResponse
	(*durationpb.Duration)(nil), // 1: google.protobuf.Duration
}
var file_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto_depIdxs = []int32{
	1, // 0: poll.PollResponse.jitter:type_name -> google.protobuf.Duration
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto_init() }
func file_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto_init() {
	if File_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto_rawDesc), len(file_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto_goTypes,
		DependencyIndexes: file_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto_depIdxs,
		MessageInfos:      file_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto_msgTypes,
	}.Build()
	File_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto = out.File
	file_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto_goTypes = nil
	file_internal_sampler_p2platency_internal_grpcpeer_proto_poll_response_proto_depIdxs = nil
}
