version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "yearly"
    target-branch: "master"
    groups:
      all-dependencies:
        patterns:
          - "*"
