services:

  jittermon:
    image: jittermon:latest
    restart: always
    depends_on:
      - grafana
      - prometheus
      - loki
      - promtail
    networks:
      - jittermon-network
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      - JITTERMON_PEER_ID=local-peer
      - JITTERMON_LOG_LEVEL=INFO
      - JITTERMON_PING_INTERVAL=1s
      - JITTERMON_PING_ADDRS=8.8.8.8:53
      - JITTERMON_JITTER_INTERVAL=1s
      - JITTERMON_JITTER_LISTEN_ADDR=:8081
      - JITTERMON_METRICS_ADDR=:8082
      - JITTERMON_USE_LOG_RECORDER=false # TODO: remove?
    env_file:
      - .env

  grafana:
    image: grafana/grafana:11.6.0
    restart: always
    networks:
      - jittermon-network
    ports:
      - "3000:3000"
    volumes:
      - jittermon-grafana-data:/var/lib/grafana
      - ./app/grafana/provisioning:/etc/grafana/provisioning
      - ./app/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=demo
      - GF_SECURITY_ADMIN_PASSWORD=demo

  prometheus:
    image: prom/prometheus:v3.3.0
    restart: always
    depends_on:
      - grafana
    networks:
      - jittermon-network
    ports:
      - "9090:9090"
    volumes:
      - jittermon-prometheus-data:/prometheus
      - ./app/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:3.4.1
    restart: always
    depends_on:
      - grafana
    networks:
      - jittermon-network
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - jittermon-loki-data:/loki
      - ./app/loki:/etc/loki

  promtail:
    image: grafana/promtail:3.4.1
    restart: always
    depends_on:
      - loki
      - prometheus
    networks:
      - jittermon-network
    volumes:
      - ./app/promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail.yml

networks:
  jittermon-network:
    driver: bridge

volumes:
  jittermon-grafana-data:
  jittermon-prometheus-data:
  jittermon-loki-data:
