# fly.toml app configuration file generated for jittermon on 2025-02-04T16:18:33-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jittermon'
primary_region = 'yyz'
kill_signal = 'SIGINT'
kill_timeout = '1m0s'

[experimental]
  cmd = ['-s', '0.0.0.0:8081', '-l', '0.0.0.0:8080']

[build]
  ignorefile = ".dockerignore"

[env]
  WAFERBW = 'nothing'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    force_https = false
    port = '8080'
    handlers = []

  [services.ports.http_options]
    h2_backend = true

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
