# fly.toml app configuration file generated for jittermon on 2025-03-07T17:35:12-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jittermon'
primary_region = 'yyz'
kill_signal = 'SIGINT'
kill_timeout = '1m0s'

[build]
  dockerfile = 'Dockerfile'

[env]
  JITTERMON_P2P_LATENCY_INTERVAL = '0.25s'
  JITTERMON_P2P_LATENCY_LISTEN_ADDR = ':8080'
  JITTERMON_LOG_LEVEL = 'INFO'
  JITTERMON_PEER_ID = 'flyio-yyz'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 8080

    [services.ports.http_options]
      h2_backend = true

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
