global:
  evaluation_interval: 2s
  scrape_interval: 2s
  scrape_timeout: 1s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText1.0.0
  - PrometheusText0.0.4
runtime:
  gogc: 75
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  track_timestamps_staleness: false
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090
- job_name: jittermon
  scrape_interval: 2s
  scrape_timeout: 1s
  honor_timestamps: true
  track_timestamps_staleness: false
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  static_configs:
  - targets:
    - jittermon:8082
