// Code generated by MockGen. DO NOT EDIT.
// Source: traceroute.go
//
// Generated by this command:
//
//	mockgen -source=traceroute.go -destination=traceroute_mocks_test.go -package=traceroute_test
//

// Package traceroute_test is a generated GoMock package.
package traceroute_test

import (
	context "context"
	reflect "reflect"

	recorder "github.com/wafer-bw/jittermon/internal/recorder"
	traceroute "github.com/wafer-bw/jittermon/internal/sampler/traceroute"
	gomock "go.uber.org/mock/gomock"
)

// MockTracer is a mock of Tracer interface.
type MockTracer struct {
	ctrl     *gomock.Controller
	recorder *MockTracerMockRecorder
	isgomock struct{}
}

// MockTracerMockRecorder is the mock recorder for MockTracer.
type MockTracerMockRecorder struct {
	mock *MockTracer
}

// NewMockTracer creates a new mock instance.
func NewMockTracer(ctrl *gomock.Controller) *MockTracer {
	mock := &MockTracer{ctrl: ctrl}
	mock.recorder = &MockTracerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracer) EXPECT() *MockTracerMockRecorder {
	return m.recorder
}

// Trace mocks base method.
func (m *MockTracer) Trace(ctx context.Context, dst string) (traceroute.Hops, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trace", ctx, dst)
	ret0, _ := ret[0].(traceroute.Hops)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Trace indicates an expected call of Trace.
func (mr *MockTracerMockRecorder) Trace(ctx, dst any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trace", reflect.TypeOf((*MockTracer)(nil).Trace), ctx, dst)
}

// MockRecorder is a mock of Recorder interface.
type MockRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockRecorderMockRecorder
	isgomock struct{}
}

// MockRecorderMockRecorder is the mock recorder for MockRecorder.
type MockRecorderMockRecorder struct {
	mock *MockRecorder
}

// NewMockRecorder creates a new mock instance.
func NewMockRecorder(ctrl *gomock.Controller) *MockRecorder {
	mock := &MockRecorder{ctrl: ctrl}
	mock.recorder = &MockRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecorder) EXPECT() *MockRecorderMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockRecorder) Record(arg0 context.Context, arg1 recorder.Sample) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Record", arg0, arg1)
}

// Record indicates an expected call of Record.
func (mr *MockRecorderMockRecorder) Record(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockRecorder)(nil).Record), arg0, arg1)
}
