// Code generated by MockGen. DO NOT EDIT.
// Source: udpptx.go
//
// Generated by this command:
//
//	mockgen -source=udpptx.go -destination=udpptx_mocks_test.go -package=udpptx_test
//

// Package udpptx_test is a generated GoMock package.
package udpptx_test

import (
	context "context"
	reflect "reflect"

	metric "go.opentelemetry.io/otel/metric"
	gomock "go.uber.org/mock/gomock"
)

// MockInt64Counter is a mock of Int64Counter interface.
type MockInt64Counter struct {
	ctrl     *gomock.Controller
	recorder *MockInt64CounterMockRecorder
	isgomock struct{}
}

// MockInt64CounterMockRecorder is the mock recorder for MockInt64Counter.
type MockInt64CounterMockRecorder struct {
	mock *MockInt64Counter
}

// NewMockInt64Counter creates a new mock instance.
func NewMockInt64Counter(ctrl *gomock.Controller) *MockInt64Counter {
	mock := &MockInt64Counter{ctrl: ctrl}
	mock.recorder = &MockInt64CounterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInt64Counter) EXPECT() *MockInt64CounterMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockInt64Counter) Add(ctx context.Context, incr int64, options ...metric.AddOption) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, incr}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Add", varargs...)
}

// Add indicates an expected call of Add.
func (mr *MockInt64CounterMockRecorder) Add(ctx, incr any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, incr}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockInt64Counter)(nil).Add), varargs...)
}

// MockFloat64Histogram is a mock of Float64Histogram interface.
type MockFloat64Histogram struct {
	ctrl     *gomock.Controller
	recorder *MockFloat64HistogramMockRecorder
	isgomock struct{}
}

// MockFloat64HistogramMockRecorder is the mock recorder for MockFloat64Histogram.
type MockFloat64HistogramMockRecorder struct {
	mock *MockFloat64Histogram
}

// NewMockFloat64Histogram creates a new mock instance.
func NewMockFloat64Histogram(ctrl *gomock.Controller) *MockFloat64Histogram {
	mock := &MockFloat64Histogram{ctrl: ctrl}
	mock.recorder = &MockFloat64HistogramMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFloat64Histogram) EXPECT() *MockFloat64HistogramMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockFloat64Histogram) Record(ctx context.Context, incr float64, options ...metric.RecordOption) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, incr}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Record", varargs...)
}

// Record indicates an expected call of Record.
func (mr *MockFloat64HistogramMockRecorder) Record(ctx, incr any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, incr}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockFloat64Histogram)(nil).Record), varargs...)
}
