{
 "title": "jittermon demo",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Remote gRPC Peer",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(jittermon_downstream_jitter_duration_seconds_sum{}[$__rate_interval])) by (src) / sum(rate(jittermon_downstream_jitter_duration_seconds_count{}[$__rate_interval])) by (src) > 0",
     "legendFormat": "downstream jitter"
    },
    {
     "expr": "sum(rate(jittermon_upstream_jitter_duration_seconds_sum{}[$__rate_interval])) by (src) / sum(rate(jittermon_upstream_jitter_duration_seconds_count{}[$__rate_interval])) by (src) > 0",
     "legendFormat": "upstream jitter"
    },
    {
     "expr": "sum(rate(jittermon_rtt_duration_seconds_sum{}[$__rate_interval])) by (src) / sum(rate(jittermon_rtt_duration_seconds_count{}[$__rate_interval])) by (src) > 0",
     "legendFormat": "ping (rtt)"
    },
    {
     "expr": "clamp_max(sum by (src) (increase(jittermon_lost_packets_total{}[$__rate_interval])) / sum by (src) (increase(jittermon_sent_packets_total{}[$__rate_interval])), 1)",
     "legendFormat": "packet loss"
    },
    {
     "expr": "sum(rate(jittermon_rtt_jitter_duration_seconds_sum{}[$__rate_interval])) by (src) / sum(rate(jittermon_rtt_jitter_duration_seconds_count{}[$__rate_interval])) by (src) > 0",
     "legendFormat": "jitter (rtt)"
    }
   ]
  },
  {
   "title": "Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\n  {compose_project=\"jittermon\",compose_service=\"jittermon\"}[$__auto]\n  | label_format level=detected_level\n)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 18 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{compose_project=\"jittermon\",compose_service=\"jittermon\"}\n| logfmt --keep-empty\n| label_format level=detected_level",
     "maxLines": 30
    }
   ]
  }
 ]
}