// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=ports_mocks_test.go -package=p2platency_test
//

// Package p2platency_test is a generated GoMock package.
package p2platency_test

import (
	context "context"
	reflect "reflect"

	recorder "github.com/wafer-bw/jittermon/internal/recorder"
	pollpb "github.com/wafer-bw/jittermon/internal/sampler/p2platency/internal/pollpb"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockRecorder is a mock of Recorder interface.
type MockRecorder struct {
	ctrl     *gomock.Controller
	recorder *MockRecorderMockRecorder
	isgomock struct{}
}

// MockRecorderMockRecorder is the mock recorder for MockRecorder.
type MockRecorderMockRecorder struct {
	mock *MockRecorder
}

// NewMockRecorder creates a new mock instance.
func NewMockRecorder(ctrl *gomock.Controller) *MockRecorder {
	mock := &MockRecorder{ctrl: ctrl}
	mock.recorder = &MockRecorderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecorder) EXPECT() *MockRecorderMockRecorder {
	return m.recorder
}

// Record mocks base method.
func (m *MockRecorder) Record(arg0 context.Context, arg1 recorder.Sample) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Record", arg0, arg1)
}

// Record indicates an expected call of Record.
func (mr *MockRecorderMockRecorder) Record(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Record", reflect.TypeOf((*MockRecorder)(nil).Record), arg0, arg1)
}

// MockGRPCClientPoller is a mock of GRPCClientPoller interface.
type MockGRPCClientPoller struct {
	ctrl     *gomock.Controller
	recorder *MockGRPCClientPollerMockRecorder
	isgomock struct{}
}

// MockGRPCClientPollerMockRecorder is the mock recorder for MockGRPCClientPoller.
type MockGRPCClientPollerMockRecorder struct {
	mock *MockGRPCClientPoller
}

// NewMockGRPCClientPoller creates a new mock instance.
func NewMockGRPCClientPoller(ctrl *gomock.Controller) *MockGRPCClientPoller {
	mock := &MockGRPCClientPoller{ctrl: ctrl}
	mock.recorder = &MockGRPCClientPollerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGRPCClientPoller) EXPECT() *MockGRPCClientPollerMockRecorder {
	return m.recorder
}

// Poll mocks base method.
func (m *MockGRPCClientPoller) Poll(ctx context.Context, in *pollpb.PollRequest, opts ...grpc.CallOption) (*pollpb.PollResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Poll", varargs...)
	ret0, _ := ret[0].(*pollpb.PollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Poll indicates an expected call of Poll.
func (mr *MockGRPCClientPollerMockRecorder) Poll(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockGRPCClientPoller)(nil).Poll), varargs...)
}
