#!/bin/sh

set -e

PREFIX="github.com/wafer-bw/jittermon"

protoc -I . --go_out=. --go_opt=default_api_level=API_OPAQUE --go_opt=module=$PREFIX --go-grpc_out=. --go-grpc_opt=default_api_level=API_OPAQUE --go-grpc_opt=module=$PREFIX ./internal/sampler/latency/peer/internal/proto/*.proto

go generate ./...
