services:

  jittermon:
    image: jittermon:latest
    networks:
      - jittermon-network
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      - JITTERMON_PEER_ID=local-peer
      - JITTERMON_LOG_LEVEL=INFO
      - JITTERMON_LATENCY_INTERVAL=1s
      - JITTERMON_LATENCY_SEND_ADDRS=
      - JITTERMON_P2P_LATENCY_INTERVAL=0.25s
      - JITTERMON_P2P_LATENCY_LISTEN_ADDR=:8081
      - JITTERMON_TRACE_INTERVAL=1s
      - JITTERMON_METRICS_ADDR=:8082
      - JITTERMON_USE_LOG_RECORDER=false
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:v3.3.0
    networks:
      - jittermon-network
    ports:
      - "9090:9090"
    volumes:
      - jittermon-remote-p2p-prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:11.6.0
    networks:
      - jittermon-network
    ports:
      - "3000:3000"
    volumes:
      - jittermon-remote-p2p-grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=demo
      - GF_SECURITY_ADMIN_PASSWORD=demo

  loki:
    image: grafana/loki:3.4.1
    networks:
      - jittermon-network
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - jittermon-remote-p2p-loki-data:/loki
      - ./loki:/etc/loki

  promtail:
    depends_on:
      - loki
    image: grafana/promtail:3.4.1
    networks:
      - jittermon-network
    volumes:
      - ./promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail.yml

networks:
  jittermon-network:
    driver: bridge

volumes:
  jittermon-remote-p2p-grafana-data:
  jittermon-remote-p2p-prometheus-data:
  jittermon-remote-p2p-loki-data:
