services:

  jittermon:
    image: jittermon:latest
    networks:
      - jittermon-network
    ports:
      - "8081:8081"
      - "8082:8082"
    environment:
      - JITTERMON_PEER_ID=localhost
      - JITTERMON_LOG_LEVEL=INFO
      - JITTERMON_INTERVAL=0.25s
      - JITTERMON_LISTEN_ADDR=:8081
      - JITTERMON_METRICS_ADDR=:8082
    env_file:
      - .env

  prometheus:
    image: prom/prometheus:latest
    networks:
      - jittermon-network
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    networks:
      - jittermon-network
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=demo
      - GF_SECURITY_ADMIN_PASSWORD=demo

  loki:
    image: grafana/loki:latest
    networks:
      - jittermon-network
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki.yml
    volumes:
      - ./loki:/etc/loki

  promtail:
    depends_on:
      - loki
    image: grafana/promtail:latest
    networks:
      - jittermon-network
    volumes:
      - ./promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail.yml

networks:
  jittermon-network:
    driver: bridge

volumes:
  grafana-data:
  prometheus-data:
