// Code generated by MockGen. DO NOT EDIT.
// Source: grpc.go
//
// Generated by this command:
//
//	mockgen -source=grpc.go -destination=grpc_mocks_test.go -package=grpcpeer_test
//

// Package grpcpeer_test is a generated GoMock package.
package grpcpeer_test

import (
	context "context"
	reflect "reflect"

	pollpb "github.com/wafer-bw/jittermon/internal/sampler/p2platencyv2/internal/grpcpeer/pollpb"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockClientPoller is a mock of ClientPoller interface.
type MockClientPoller struct {
	ctrl     *gomock.Controller
	recorder *MockClientPollerMockRecorder
	isgomock struct{}
}

// MockClientPollerMockRecorder is the mock recorder for MockClientPoller.
type MockClientPollerMockRecorder struct {
	mock *MockClientPoller
}

// NewMockClientPoller creates a new mock instance.
func NewMockClientPoller(ctrl *gomock.Controller) *MockClientPoller {
	mock := &MockClientPoller{ctrl: ctrl}
	mock.recorder = &MockClientPollerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientPoller) EXPECT() *MockClientPollerMockRecorder {
	return m.recorder
}

// Poll mocks base method.
func (m *MockClientPoller) Poll(ctx context.Context, in *pollpb.PollRequest, opts ...grpc.CallOption) (*pollpb.PollResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Poll", varargs...)
	ret0, _ := ret[0].(*pollpb.PollResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Poll indicates an expected call of Poll.
func (mr *MockClientPollerMockRecorder) Poll(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockClientPoller)(nil).Poll), varargs...)
}
