name: checks

on:
  push:
    branches:
      - main
    paths:
      - "internal/**"
      - ".github/workflows/**/*.yml"
      - "scripts/**"
      - "main.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches:
      - main
    paths:
      - "internal/**"
      - ".github/workflows/**/*.yml"
      - "scripts/**"
      - "main.go"
      - "go.mod"
      - "go.sum"

jobs:

  setup:
    name: setup
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      fail-fast: true
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true

  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      fail-fast: true
    needs: setup
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Run go generate
        run: go generate ./... && git diff --exit-code
      - name: Setup buf
        uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - name: Generate proto stubs
        run: buf generate
      - name: Run go build
        run: go build -o /dev/null ./...

  clean:
    name: clean
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      fail-fast: true
    needs: setup
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Run go mod tidy
        run: go mod tidy && git diff --exit-code
      - name: Run go mod verify
        run: go mod verify
      - name: Run go fix
        run: go fix ./...
      - name: govulncheck
        run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...
      - name: Setup buf
        uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - name: Run GCI
        run: go run github.com/daixiang0/gci write -s standard -s default --skip-generated .
      - name: Run buf
        run: buf format -w

  lint:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 4
    strategy:
      fail-fast: true
    needs: setup
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Run Go linting
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
      - name: Set up buf
        uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - name: Run proto linting
        run: buf lint

  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true
    needs: setup
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Run tests
        run: go test -shuffle=on -v -count=1 -race -failfast -timeout=30s -covermode=atomic -coverprofile=coverage.txt `go list ./... | grep -v /internal/gen`
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: wafer-bw/jittermon

  benchmark:
    name: benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      fail-fast: true
    needs: setup
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Run benchmarks
        run: go test -v -shuffle=on -run=- -bench=. -benchtime=1x -timeout=1m ./...
